name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"
          cache: true
          cache-dependency-path: ./BTCPayServer.Plugins.Boltz/packages.lock.json

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Restore dependencies
        run: dotnet restore BTCPayServer.Plugins.Boltz --locked-mode

      - name: Build plugin
        run: dotnet build BTCPayServer.Plugins.Boltz --configuration Release --no-restore

      - name: Install Node.js dependencies
        working-directory: ./docs
        run: npm ci

      - name: Prettier docs
        working-directory: ./docs
        run: npm run prettier:check

      - name: Build docs
        working-directory: ./docs
        run: npm run docs:build

      - name: Restore test dependencies
        run: dotnet restore BTCPayServer.Plugins.Boltz.Tests

      - name: Build tests
        run: dotnet build BTCPayServer.Plugins.Boltz.Tests --configuration Release --no-restore

      - name: Run fast tests
        run: make test-fast

      - name: Setup Boltz regtest
        env:
          COMPOSE_PROFILES: btcpay,ci
        run: cd regtest && ./start.sh

      - name: Run integration tests
        run: make test-integration

      - name: Install Playwright browsers
        run: pwsh ./BTCPayServer.Plugins.Boltz.Tests/bin/Release/net8.0/playwright.ps1 install chromium

      - name: Run Playwright tests
        run: make test-playwright

      - name: Upload Playwright artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-artifacts
          path: |
            **/playwright-traces/
            **/screenshots/
